### ISSUE TITLE
Unable to install libneurosim

### ISSUE THREAD

**Issue by ShashShukla** [INCF/libneurosim#6]
I am running Ubuntu 16.04 LTS.
I downloaded and extracted the repo and then did the following:
1) aclocal
2) ./autogen.sh
3) ./configure
4) make

make gave me the following output error:
```
Making all in libneurosim
make[2]: Entering directory '/home/shashwat/Desktop/libneurosim-master/libneurosim'
depbase=`echo conngen/connection_generator.lo | sed 's|[^/]*$|.deps/&|;s|\.lo$||'`;\
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../libltdl     -MT conngen/connection_generator.lo -MD -MP -MF $depbase.Tpo -c -o conngen/connection_generator.lo conngen/connection_generator.cpp &&\
mv -f $depbase.Tpo $depbase.Plo
libtool: Version mismatch error.  This is libtool 2.4.2, but the
libtool: definition of this LT_INIT comes from libtool 2.4.6.
libtool: You should recreate aclocal.m4 with macros from libtool 2.4.2
libtool: and run autoconf again.
Makefile:518: recipe for target 'conngen/connection_generator.lo' failed
make[2]: *** [conngen/connection_generator.lo] Error 63
make[2]: Leaving directory '/home/shashwat/Desktop/libneurosim-master/libneurosim'
Makefile:423: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/shashwat/Desktop/libneurosim-master'
Makefile:355: recipe for target 'all' failed
make: *** [all] Error 2
```
Any help would be greatly appreciated, thanks!

**Comment by jougs** [comment]
This Stack Overflow entry has a possible answer: https://stackoverflow.com/questions/3096989/libtool-version-mismatch-error
Can you please report back if that solves the problem for you?

**Comment by ShashShukla** [comment]
Sorry for the late reply...
I had scoured all the forums and did indeed try the fixes mentioned in the above SO entry before opening this issue. None of them worked.

**Comment by mdjurfeldt** [comment]
The problem seems to be that the code created by libtoolize = libtool
ltmain etc does not match the libtool m4 macros inserted into aclocal.m4 by
aclocal. This should not normally happen.

Did you checkout a clean copy of libneurosim from github or was there
another source?

Is your Ubuntu installation clean or are there aclocal directories, for
example under /usr/local, which could mess things up?

Is your set of environment variables clean such that non-standard paths are
not specified?

Do you have the Ubuntu 16.04 standard versions of automake, autoconf and
libtool installed or are there other versions or even multiple versions
installed?

I would suggest trying to make your environment as clean as possible, check
that aclocal, autoconf, automake and libtoolize all come from a sensible
place in the filesystem (/usr/bin), delete the libneurosim trees (both
source and build), checkout github master and try again.

Best regards,
Mikael

Den 15 sep. 2017 11:33 AM skrev "Shashwat Shukla" <notifications@github.com
>:

Sorry for the late reply...
I had scoured all the forums and did indeed try the fixes mentioned in the
above SO entry before opening this issue. None of them worked.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/INCF/libneurosim/issues/6#issuecomment-329731873>, or mute
the thread

**Comment by ShashShukla** [comment]
Hi Mikael,

Thank you for your very detailed reply. I realised that the problem was with Anaconda. It had overridden my libtool install and had itself being using libtool version 2.4.2 instead of 2.4.6.
Uninstalling libtool from the Anaconda distribution and reinstalling libtool-bin solved the problem for me.

Thanks a lot for your help!

Cheers,
Shashwat

**Comment by mdjurfeldt** [comment]
Anaconda is fundamentally broken.

It's crazy to distribute own versions of system libraries and utilities.
That should be done in a virtual machine or docker image. Else, you need to
explicitly keep track of dependencies like in guix.

Good that you found out!

Den 18 sep. 2017 9:46 PM skrev "Shashwat Shukla" <notifications@github.com>:

Hi Mikael,

Thank you for your very detailed reply. I realised that the problem was
with Anaconda. It had overridden my libtool install and had itself being
using libtool version 2.4.2 instead of 2.4.6.
Uninstalling libtool from the Anaconda distribution and reinstalling
libtool-bin solved the problem for me.

Thanks a lot for your help!

Cheers,
Shashwat

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/INCF/libneurosim/issues/6#issuecomment-330335094>, or mute
the thread
